//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace jobsity.Repository
{
    
    
    public class MessageMetaData
    {
    	[Key]
        [Required]
        public virtual int IdMessage
        {
            get;
            set;
        }
    	
        [StringLength(4000, ErrorMessage="Max length is 4000")]
        [Required]
        public virtual string Message1
        {
            get;
            set;
        }
        [Required]
        public virtual int IdUser
        {
            get;
            set;
    
        }
        [Required]
        public virtual System.DateTime Date
        {
            get;
            set;
        }
    }
}
