//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace jobsity.Repository
{
    
    
    public class RoleMetaData
    {
    	[Key]
        [Required]
        public virtual int IdRole
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="Max length is 50")]
        public virtual string Name
        {
            get;
            set;
        }
    }
}
