//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace jobsity.Repository
{
    
    
    public class UserMetaData
    {
    	
        [StringLength(100, ErrorMessage="Max length is 100")]
        [Required]
        public virtual string FirstName
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="Max length is 100")]
        [Required]
        public virtual string LastName
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="Max length is 100")]
        [Required]
        public virtual string Email
        {
            get;
            set;
        }
    	
        [StringLength(500, ErrorMessage="Max length is 500")]
        [Required]
        public virtual string Password
        {
            get;
            set;
        }
        public virtual Nullable<int> IdRole
        {
            get;
            set;
    
        }
    	[Key]
        [Required]
        public virtual int IdUser
        {
            get;
            set;
        }
    }
}
